name: CI

on:
  push:
    branches:
    - main

env:
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  # add public code coverage reports
  coverage:
    name: unit test coverage
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: "make unit-test-cover"
    - uses: codecov/codecov-action@v2

  # build and push to docker.io
  build:
    name: docker build & push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      # platform = linux/amd64 only for speed
      - name: Build and push Docker image
        run: "make docker-buildx PLATFORMS=linux/amd64 IMG=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}"